// Regenerates src/i18n/generated/{en,es}.ts from the app repo's locale files.
// Run: npm run port:copy      (APP_REPO overrides the sibling-checkout default)
import { mkdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";

const APP_REPO = process.env.APP_REPO ?? resolve(process.cwd(), "../wiz_scheduler");
const LOCALES = ["en", "es"];
const OUT_DIR = resolve(process.cwd(), "src/i18n/generated");

function pick(t) {
  return {
    common: { appName: t.common.appName },
    login: { signIn: t.login.signIn },
    register: { registerBtn: t.register.registerBtn },
    landing: t.landing,
    features: t.features,
    gdpr: {
      privacyPolicy: t.gdpr.privacyPolicy,
      termsOfService: t.gdpr.termsOfService,
      dpa: t.gdpr.dpa,
      version: t.gdpr.version,
      effectiveDate: t.gdpr.effectiveDate,
      processors: t.gdpr.processors,
      processorName: t.gdpr.processorName,
      processorPurpose: t.gdpr.processorPurpose,
      processorLocation: t.gdpr.processorLocation,
    },
  };
}

mkdirSync(OUT_DIR, { recursive: true });
for (const locale of LOCALES) {
  const file = resolve(APP_REPO, `frontend/src/i18n/${locale}.ts`);
  const mod = await import(pathToFileURL(file).href);
  const subset = pick(mod.default);
  const body =
    `// Generated by scripts/port-copy.mjs from the app repo's ${locale}.ts. Do not edit by hand.\n` +
    `export default ${JSON.stringify(subset, null, 2)};\n`;
  writeFileSync(resolve(OUT_DIR, `${locale}.ts`), body);
  console.log(`wrote src/i18n/generated/${locale}.ts`);
}
